#!/bin/sh /etc/rc.common

START=15
USE_PROCD=1

get_next_port_split() {
    devlink port show | grep -m1 split_group | sed 's/: .*//'
}

split_port() {
    local split_config="$1"
    local device
    local count
    local error

    config_get device "$split_config" "device"
    config_get count  "$split_config" "count"

    if [ -z "$device" ]; then
        echo "Missing device for port split $split_config"
        return 1
    fi

    if [ -z "$count" ]; then
        echo "Missing count for $device port split"
        return 1
    fi

    error="$(devlink port split "$device" count "$count" 2>&1)"

    if [ -n "$error" ]; then
        echo "$device port split error"
        echo "$error"
        return 1
    fi
}

unsplit_ports() {
    local port="$(get_next_port_split)"

    while [ -n "$port" ]; do
        devlink port unsplit "$port"
        port="$(get_next_port_split)"
    done
}

start_service() {
	config_load network
    config_foreach split_port "port_split"
}

stop_service() {
	unsplit_ports
}

reload_service() {
    unsplit_ports
    start
}

service_triggers() {
    procd_add_reload_trigger network
}
